# Generated by Django 3.2.24 on 2024-03-01 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('Reclamacao', 'Reclamação'), ('Denuncia', 'Denúncia'), ('Sugestao', 'Sugestão'), ('Critica', 'Crítica'), ('Elogio', 'Elogio'), ('Mensagem', 'Mensagem')], max_length=20)),
                ('mensagem', models.TextField()),
                ('data_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('bairro_sao_goncalo', models.CharField(choices=[('Alcantara', 'Alcântara'), ('Almerinda', 'Almerinda'), ('Amendoeira', 'Amendoeira'), ('Anaia Grande', 'Anaia Grande'), ('Anaia Pequeno', 'Anaia Pequeno'), ('Antonina', 'Antonina'), ('Arsenal', 'Arsenal'), ('Arrastao', 'Arrastão'), ('Barro Vermelho', 'Barro Vermelho'), ('Barracao', 'Barracão'), ('Boa Vista', 'Boa Vista'), ('Boacu', 'Boaçu'), ('Bom Retiro', 'Bom Retiro'), ('Brasilandia', 'Brasilândia'), ('Camaraao', 'Camarão'), ('Centro', 'Centro'), ('Colubande', 'Colubandê'), ('Convanca', 'Convanca'), ('Cruzeiro do Sul', 'Cruzeiro do Sul'), ('Eliane', 'Eliane'), ('Engenho do Rocado', 'Engenho do Roçado'), ('Engenho Pequeno', 'Engenho Pequeno'), ('Estrela do Norte', 'Estrela do Norte'), ('Fazenda dos Mineiros', 'Fazenda dos Mineiros'), ('Galo Branco', 'Galo Branco'), ('Gebara', 'Gebara'), ('Gradim', 'Gradim'), ('Guarani', 'Guarani'), ('Guaxindiba', 'Guaxindiba'), ('Ieda', 'Ieda'), ('Ipiiba', 'Ipiíba'), ('Itaoca', 'Itaoca'), ('Itauna', 'Itaúna'), ('Jardim Amendoeira', 'Jardim Amendoeira'), ('Jardim Catarina', 'Jardim Catarina'), ('Jardim Nova Republica', 'Jardim Nova República'), ('Joquei', 'Joquei'), ('Lagoinha', 'Lagoinha'), ('Laranjal', 'Laranjal'), ('Lindo Parque', 'Lindo Parque'), ('Luiz Cacador', 'Luiz Caçador'), ('Marambaia', 'Marambaia'), ('Maria Paula', 'Maria Paula'), ('Mangueira', 'Mangueira'), ('Miriambi', 'Miriambi'), ('Monjolo', 'Monjolo'), ('Morro do Castro', 'Morro do Castro'), ('Mutondo', 'Mutondo'), ('Mutuaguacu', 'Mutuaguaçu'), ('Mutuapira', 'Mutuapira'), ('Neves', 'Neves'), ('Nova Cidade', 'Nova Cidade'), ('Novo Mexico', 'Novo México'), ('Pacheco', 'Pacheco'), ('Palmeira', 'Palmeira'), ('Paraiso', 'Paraíso'), ('Parada 40', 'Parada 40'), ('Patronato', 'Patronato'), ('Pita', 'Pita'), ('Porto da Madama', 'Porto da Madama'), ('Porto da Pedra', 'Porto da Pedra'), ('Porto do Rosa', 'Porto do Rosa'), ('Porto Novo', 'Porto Novo'), ('Porto Velho', 'Porto Velho'), ('Recanto das Acacias', 'Recanto das Acácias'), ('Raul Veiga', 'Raul Veiga'), ('Rio do Ouro', 'Rio do Ouro'), ('Rocha', 'Rocha'), ('Rosane', 'Rosane'), ('Sacramento', 'Sacramento'), ('Salgueiro', 'Salgueiro'), ('Santa Catarina', 'Santa Catarina'), ('Santa Isabel', 'Santa Isabel'), ('Santa Luzia', 'Santa Luzia'), ('Sao Miguel', 'São Miguel'), ('Tiradentes', 'Tiradentes'), ('Trindade', 'Trindade'), ('Tribobo', 'Tribobó'), ('Venda da Cruz', 'Venda da Cruz'), ('Vila Candoza', 'Vila Candoza'), ('Vila Lara', 'Vila Lara'), ('Vila Lage', 'Vila Lage'), ('Vila Tres', 'Vila Três'), ('Vista Alegre', 'Vista Alegre')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'Mulher'), ('H', 'Homem')], max_length=10)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('titulo_eleitor', models.CharField(max_length=20)),
                ('zona_eleitoral', models.CharField(blank=True, max_length=10, null=True)),
                ('secao_eleitoral', models.CharField(blank=True, max_length=10, null=True)),
                ('local_de_votacao', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('nao_consta', models.BooleanField(default=False)),
                ('lideranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.lideranca')),
            ],
        ),
    ]
