# Generated by Django 3.2 on 2024-05-27 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bairro_de_atuacao', models.CharField(choices=[('Alcântara', 'Alcântara'), ('Almerinda', 'Almerinda'), ('Amendoeira', 'Amendoeira'), ('Anaia Grande', 'Anaia Grande'), ('Anaia Pequeno', 'Anaia Pequeno'), ('Antonina', 'Antonina'), ('Arsenal', 'Arsenal'), ('Arrastão', 'Arrastão'), ('Barro Vermelho', 'Barro Vermelho'), ('Barracão', 'Barracão'), ('Boa Vista', 'Boa Vista'), ('Boaçu', 'Boaçu'), ('Bom Retiro', 'Bom Retiro'), ('Brasilândia', 'Brasilândia'), ('Camarão', 'Camarão'), ('Centro', 'Centro'), ('Colubandê', 'Colubandê'), ('Convança', 'Convança'), ('Cruzeiro do Sul', 'Cruzeiro do Sul'), ('Eliane', 'Eliane'), ('Engenho do Rocado', 'Engenho do Rocado'), ('Engenho Pequeno', 'Engenho Pequeno'), ('Estrela do Norte', 'Estrela do Norte'), ('Fazenda dos Mineiros', 'Fazenda dos Mineiros'), ('Galo Branco', 'Galo Branco'), ('Gebara', 'Gebara'), ('Gradim', 'Gradim'), ('Guarani', 'Guarani'), ('Guaxindiba', 'Guaxindiba'), ('Ieda', 'Ieda'), ('Ipiíba', 'Ipiíba'), ('Itaoca', 'Itaoca'), ('Itaúna', 'Itaúna'), ('Jardim Amendoeira', 'Jardim Amendoeira'), ('Jardim Catarina', 'Jardim Catarina'), ('Jardim Nova República', 'Jardim Nova República'), ('Jockey', 'Jockey'), ('Lagoinha', 'Lagoinha'), ('Laranjal', 'Laranjal'), ('Lindo Parque', 'Lindo Parque'), ('Luiz Caçador', 'Luiz Caçador'), ('Marambaia', 'Marambaia'), ('Maria Paula', 'Maria Paula'), ('Mangueira', 'Mangueira'), ('Miriambi', 'Miriambi'), ('Monjolos', 'Monjolos'), ('Morro do Castro', 'Morro do Castro'), ('Mutondo', 'Mutondo'), ('Mutuaguacu', 'Mutuaguacu'), ('Mutuapira', 'Mutuapira'), ('Neves', 'Neves'), ('Nova Cidade', 'Nova Cidade'), ('Novo México', 'Novo México'), ('Pacheco', 'Pacheco'), ('Palmeiras', 'Palmeiras'), ('Paraíso', 'Paraíso'), ('Parada 40', 'Parada 40'), ('Patronato', 'Patronato'), ('Pita', 'Pita'), ('Porto da Madama', 'Porto da Madama'), ('Porto da Pedra', 'Porto da Pedra'), ('Porto do Rosa', 'Porto do Rosa'), ('Porto Novo', 'Porto Novo'), ('Porto Velho', 'Porto Velho'), ('Recanto das Acácias', 'Recanto das Acácias'), ('Raul Veiga', 'Raul Veiga'), ('Rio do Ouro', 'Rio do Ouro'), ('Rocha', 'Rocha'), ('Rosane', 'Rosane'), ('Sacramento', 'Sacramento'), ('Salgueiro', 'Salgueiro'), ('Santa Catarina', 'Santa Catarina'), ('Santa Isabel', 'Santa Isabel'), ('Santa Luzia', 'Santa Luzia'), ('São Miguel', 'São Miguel'), ('Tiradentes', 'Tiradentes'), ('Trindade', 'Trindade'), ('Tribobó', 'Tribobó'), ('Venda da Cruz', 'Venda da Cruz'), ('Vila Candoza', 'Vila Candoza'), ('Vila Lara', 'Vila Lara'), ('Vila Lage', 'Vila Lage'), ('Vila Três', 'Vila Três'), ('Vista Alegre', 'Vista Alegre'), ('Várzea das Moças', 'Várzea das Moças'), ('Ilha', 'Ilha'), ('Coelho', 'Coelho'), ('Largo da Ideia', 'Largo da Ideia'), ('Tenente Jardim', 'Tenente Jardim'), ('Vila Yara', 'Vila Yara'), ('Zé Garoto', 'Zé Garoto'), ('Zumbi', 'Zumbi')], max_length=100)),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_de_atuacao', models.CharField(max_length=100)),
                ('acordo', models.FileField(blank=True, null=True, upload_to='acordos/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='liderancas/')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Mulher'), ('H', 'Homem')], max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('titulo_eleitor', models.CharField(max_length=20, unique=True)),
                ('zona_eleitoral', models.CharField(blank=True, max_length=10, null=True)),
                ('secao_eleitoral', models.CharField(blank=True, max_length=10, null=True)),
                ('local_de_votacao', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('nao_consta', models.BooleanField(default=False)),
                ('apto_a_votar', models.BooleanField(default=False)),
                ('votante', models.BooleanField(default=False)),
                ('filhos', models.BooleanField(default=False)),
                ('grau_de_influencia', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('nenhum', 'Nenhum')], max_length=10)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lideranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.lideranca')),
            ],
            options={
                'permissions': [('can_view_own_pessoa', 'Can view own pessoa')],
            },
        ),
    ]
