# Generated by Django 3.2.24 on 2024-02-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiaoatuacao',
            name='bairros',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='contato',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='profissao',
            new_name='cidade',
        ),
        migrations.RemoveField(
            model_name='lideranca',
            name='coordenadas',
        ),
        migrations.RemoveField(
            model_name='lideranca',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='lideranca',
            name='regiao_atuacao',
        ),
        migrations.AddField(
            model_name='lideranca',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_mae',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='secao_eleitoral',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='zona_eleitoral',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
        migrations.DeleteModel(
            name='RegiaoAtuacao',
        ),
    ]
