# Generated by Django 3.2.24 on 2024-02-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20240224_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nao_consta',
            field=models.BooleanField(default=False),
        ),
    ]
