# Generated by Django 3.2.24 on 2024-02-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_pessoa_nao_consta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cep_temporario',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='secao_eleitoral',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Mulher'), ('H', 'Homem')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='zona_eleitoral',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
