# Generated by Django 3.2.24 on 2024-02-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20240224_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cep_temporario',
        ),
    ]
