# Generated by Django 3.2.24 on 2024-02-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_remove_pessoa_cep_temporario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
