# Generated by Django 3.2.24 on 2024-02-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_pessoa_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
