# Generated by Django 5.0.2 on 2024-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_pessoa_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
