# Generated by Django 5.0.2 on 2024-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_pessoa_bairro_alter_pessoa_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('Reclamacao', 'Reclamacao'), ('Denuncia', 'Denuncia'), ('Sugestao', 'Sugestao'), ('Critica', 'Critica'), ('Elogio', 'Elogio'), ('Mensagem', 'Mensagem')], max_length=20)),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
