# Generated by Django 5.0.2 on 2024-02-26 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='data_hora_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
