# Generated by Django 5.0.2 on 2024-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_pergunta_bairro_sao_goncalo_alter_pergunta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
